services:
  - type: web
    name: wireguard
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: SERVERPORT
        value: "5120"
    ports:
      - port: 5120
        protocol: udp
    disk:
      name: wireguard-data
      mountPath: /config
      sizeGB: 1
